# Generated by Django 2.2 on 2020-04-25 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='name',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(default='Sin categoría', max_length=25),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(default='Sin descripción', max_length=200),
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default='Nombre', max_length=25),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=2)),
                ('ciudad', models.CharField(max_length=30)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalogo.Producto')),
            ],
        ),
    ]
