# Generated by Django 2.2 on 2020-04-25 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogo', '0002_auto_20200425_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='nombre',
        ),
    ]
