# Generated by Django 2.2 on 2020-04-25 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Analitica', '0001_initial'),
        ('Tienda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='inicio',
            new_name='fecha',
        ),
        migrations.AddField(
            model_name='tienda',
            name='zona',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Analitica.Zona'),
        ),
    ]
