# Generated by Django 2.2 on 2020-04-25 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Catalogo', '0005_auto_20200425_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='Sin nombre', max_length=25)),
                ('ciudad', models.CharField(default='Sin nombre', max_length=25)),
                ('pais', models.CharField(default='Sin nombre', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now=True)),
                ('descripcion', models.CharField(default='NA', max_length=80)),
                ('productos', models.ManyToManyField(to='Catalogo.Producto')),
                ('zona', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Analitica.Zona')),
            ],
        ),
    ]
